# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-03 23:10
from __future__ import unicode_literals

import blogger.apps.entradas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='imagen_portada',
            field=models.ImageField(default='img/none.jpg', upload_to=blogger.apps.entradas.models.image_directory_path),
        ),
    ]
