# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-04 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0002_auto_20170703_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='comentario_entrada',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
