# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-10 18:58
from __future__ import unicode_literals

import blogger.apps.multimedia.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_multimedia', models.CharField(max_length=45)),
                ('slug_multimedia', models.CharField(max_length=45)),
                ('tipo_multimedia', models.CharField(choices=[('v', 'Video'), ('f', 'Foto')], max_length=1)),
                ('image_multimedia', models.ImageField(blank=True, null=True, upload_to=blogger.apps.multimedia.models.image_directory_path)),
                ('video_multimedia', models.CharField(blank=True, max_length=255, null=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Institucion')),
            ],
        ),
    ]
