# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-10 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='slug_multimedia',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
