# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-17 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0004_auto_20170711_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioMultimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=1000)),
                ('multimedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia.Multimedia')),
            ],
        ),
    ]
