# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-20 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170630_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='foto_usuario',
            field=models.ImageField(default='img/none.jpg', upload_to='img/usuarios/'),
        ),
    ]
