# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-20 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_foto_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='rol',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
