# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-26 18:14
from __future__ import unicode_literals

import blogger.apps.principal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(max_length=50)),
                ('slug_institucion', models.SlugField(blank=True, max_length=80, null=True, unique=True)),
                ('logo_institucion', models.ImageField(upload_to=blogger.apps.principal.models.image_directory_path)),
                ('descripcion_institucion', models.CharField(max_length=2000)),
                ('image_back_institucion', models.ImageField(upload_to=blogger.apps.principal.models.image_directory_path)),
            ],
        ),
    ]
