# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-24 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_suscripcionentrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='descripcion_institucion',
            field=models.CharField(max_length=10000),
        ),
    ]
