# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-26 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_institucion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1),
        ),
    ]
