# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-24 20:14
from __future__ import unicode_literals

import blogger.apps.principal.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_auto_20170725_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucionslider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('foto', models.ImageField(upload_to=b'', verbose_name=blogger.apps.principal.models.image_directory_path)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Institucion')),
            ],
        ),
    ]
