# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-24 20:22
from __future__ import unicode_literals

import blogger.apps.principal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_institucionslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img/')),
                ('titulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='institucionslider',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='institucionslider',
            name='foto',
            field=models.ImageField(upload_to=blogger.apps.principal.models.image_directory_path),
        ),
    ]
